project:
  type: website

# comments: 
#   hypothesis: true

website:
  title: "🌲 Github Policies"
  # author: DIQA 
  # date: today
  search: true
  repo-url: https://github.com/NW-PaGe/standards
  repo-actions: [source,edit,issue]
  
  navbar: 
    background: primary
    left: 
      - text: Home
        href: index.qmd
      - text: Github Policies
        menu:
          - href: gh/security.qmd
            text: "0: Security Standards"
          - href: gh/lic.qmd
            text: "1: Choosing a License"
          - href: gh/policies.qmd
            text: "2: Repo Policies"
          - href: gh/reproduce.qmd
            text: "3: Reproducibility"
      - text: AWS Policies
        menu:
          - href: aws/aws_index.qmd
            text: "0: AWS Policies"
      - text: Azure Policies
        menu:
          - href: azure/azure_index.qmd
            text: "0: Azure Policies"
      
            
      # where should this go? could be internal resource, 
      # specific to what we do should be internal
      # maybe eventually move out when restructure needed
      - text: Guides
        href: tools/index.qmd


            
            
    search: true
    # logo: images/doh_logo.png
    pinned: false
    
    right:
      - icon: github
        href: https://github.com/NW-PaGe/standards
        aria-label: GitHub
    
  page-footer:
    left: "🍦"
    background: "#440154ff"
    
    

# bibliography: references.bib


format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1000px
    #   margin-width: 300px
    #   gutter-width: 1.5rem
    theme: 
      - cosmo
      - assets/styles.scss
    scss: assets/styles.scss
    title-block-banner: true
    # css: styles.css
    toc: true
    # number-depth: 3
    # toc-depth: 3
    highlight-style: assets/custom.theme
    link-external-newwindow: true
    number-sections: true
    # code-fold: show
    code-overflow: wrap
    # page-layout: full
    backgroundcolor: "#f8f9fa"
    # header-includes: |
    #   <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/metropolitano" type="text/css"/>
# mainfont: Franklin Gothic   
    
    
execute: 
  error: true
  freeze: false



