project:
  type: website

# comments: 
#   hypothesis: true

website:
  title: NW-COE Policies
  # author: DIQA 
  # date: today
  search: true
  repo-url: https://github.com/NW-PaGe/standards
  repo-actions: [source,edit,issue]
  
  # navbar: 
  #   background: primary
  #   left: 
  #     - text: Home
  #       href: index.qmd
  #     - text: Github Policies
  #       menu:
  #         - href: gh/security.qmd
  #           text: "0: Security Standards"
  #         - href: gh/lic.qmd
  #           text: "1: Choosing a License"
  #         - href: gh/policies.qmd
  #           text: "2: Repo Policies"
  #         - href: gh/reproduce.qmd
  #           text: "3: Reproducibility"
  #     - text: AWS Policies
  #       menu:
  #         - href: aws/aws_index.qmd
  #           text: "0: AWS Policies"
  #     - text: Azure Policies
  #       menu:
  #         - href: azure/azure_index.qmd
  #           text: "0: Azure Policies"

  navbar: 
    logo: images/nwpage_tree_logo.png
    background: primary
    left: 
      - text: Github
        file: gh/index.qmd
      - text: AWS
        file: aws/aws_index.qmd
      - text: Azure
        file: azure/azure_index.qmd

    search: true
    # logo: images/doh_logo.png
    pinned: false
    
    right:
      - icon: github
        href: https://github.com/NW-PaGe/standards
        aria-label: GitHub
      - icon: file-richtext
        href: https://nwpage.org/
        aria-label: NW-PaGe

  sidebar:
    # background: '#f8f9fa'
    # alignment: left
    # style: floating
    # border: true
    # search: true
    - id: gh
      collapse-level: 2
      contents:
        - section: "Github"
          href: gh/index.qmd
          contents: 
          - section: "Policies"
            contents:
              - gh/security.qmd
              - gh/policies.qmd
              - gh/lic.qmd
              - gh/reproduce.qmd
          - section: "Tutorials"
            contents:
              - gh/release.qmd
              - gh/renv.qmd
              - gh/templates.qmd
              - gh/git.qmd
              - gh/how_to.qmd
              # - gh/*.qmd # this glob should work but it's not...

    - id: aws
    - title: "AWS Policies"
      collapse-level: 2
      background: '#f8f9fa'
      alignment: left
      style: floating
      border: true
      search: true
      align: left
      contents:
        - aws/aws_index.qmd

    - id: azure
    - title: "Azure Policies"
      collapse-level: 2
      background: '#f8f9fa'
      alignment: left
      style: floating
      border: true
      search: true
      align: left
      contents:
        - azure/azure_index.qmd
    
  page-footer:
    left: "🍦"
    background: "#fdfdfd"
    
    

# bibliography: references.bib


format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1100px
    #   margin-width: 300px
    #   gutter-width: 1.5rem
    theme: 
      - cosmo
      - assets/styles.scss
    scss: assets/styles.scss
    title-block-banner: false
    # css: styles.css
    toc: true
    # number-depth: 3
    # toc-depth: 3
    # highlight-style: assets/custom.theme
    highlight-style: printing
    link-external-newwindow: false
    number-sections: false
    # code-fold: show
    code-overflow: wrap
    # page-layout: full
    backgroundcolor: "#fdfdfd"
    # header-includes: |
    #   <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/metropolitano" type="text/css"/>
# mainfont: Franklin Gothic   
    
    
execute: 
  error: true
  freeze: false



