---
title: Quickstart - Create a Public Repo
description: Steps you need to follow to create a public repo and make sure it is secure
date: 8/16/2024
date-modified: last-modified
author: 
  - name: Frank Aragona
    email: frank.aragona@doh.wa.gov
---


If you need to make a public repo, this quick start guide is for you. **Please meet with Frank Aragona frank.aragona@doh.wa.gov before creating a public repo.** 

# Checklist

- [ ] Submit a request (service central ticket) to join a public GitHub organization
- [ ] Review items that are **prohibited** from being in a repo
- [ ] Add security guardrails; `.gitignore`
- [ ] Create global security hooks for all your repos
- [ ] Make a _private_ staging repo to make sure everything is clean
- [ ] Perform secret scanning on your repo
- [ ] Add a License 
- [ ] Make branch protections
- [ ] Copy over the _cleaned_ main branch from private repo into new public repo
- [ ] Add a README and consider adding a Github page for documentation

:::{.panel-tabset}

# Access

Our organization has multiple public Github orgs. If you are internal to Washington State Department of Health, you will need to submit a Service Central Request for access. Please reach out to frank.aragona@doh.wa.gov for help.

# Github Security

**Please read all of the [security guidelines here](security.qmd)**

The guide will go over

- what data/code is not allowed in a public repo
- security layers you need to prevent leaks
- converting private code to public repositories
- installation of pre-commit hooks to prevent leaks

# Building a Public Repo 

If you have an existing private repo that needs to be public, please follow these steps:

- [repo cleaning guides](https://nw-page.github.io/standards/gh/security.html#pushing-private-code-to-public-repos)
- [code scanning](https://nw-page.github.io/standards/gh/security.html#secret-scanning)

# Licensing

- [license rules](https://nw-page.github.io/standards/gh/lic.html)

# Repo tips/advice

- [org policies](https://nw-page.github.io/standards/gh/policies.html)
- [make your repo reproducible](https://nw-page.github.io/standards/gh/reproduce.html)
- [repo documentation](https://nw-page.github.io/standards/gh/how_to.html)
- [virtual environments](https://nw-page.github.io/standards/gh/renv.html)
- [git/github help, and how to collaborate on a repo](contribute.qmd)

:::
